image: node:14.15.0

cache:
  paths:
  - ElectronJSApp/node_modules/

all_tests:
  tags:
    - docker
  environment:
    - DISPLAY=:99
    - NODE_ENV=test 
  script:
    - Xvfb :99 -ac &
    - sleep 5
    - cd ElectronJSApp/
    - npm install
    - npm test
