default:
  image: node:14.15.0
  
  tags: 
    - docker 
    
  services:
    - selenium/standalone-chrome:latest

test:
  script:
    - npm install electron-chromedriver
    - ./node_modules/.bin/chromedriver
    - cd ElectronJSApp/
    - npm install
    - npm test