default:
  image: node:14.15.0
  before_script:
    - echo "Test and Build pipelines" 
  
cache:
  paths:
  - ElectronJSApp/node_modules/

stages:
  - build
  - test
  - deploy

job1:
  tags:
    - docker
  before_script: 
    - cd ElectronJSApp/
    - npm install
  script:
    - npm test
