# This template uses jdk8 for verifying and deploying images

image: maven:3.6.3-jdk-11

cache:
  paths:
    - ThalesArc/
    - target/

test:
  tags:
    - docker
  stage: test
  script:
    - cd ThalesArc
    - mvn dependency:unpack
    - mvn test

