default:
  image: node:14.15.0
  
  tags: 
    - docker 
    
  services:
    - selenium/standalone-chrome:latest

  before_script:
    - bundle install

test:
  script:
    - cd ElectronJSApp/
    - npm install
    - npm test