default:
  image: node:14.15.0
  
  tags: 
    - docker 
    
  services:
    - arendjan123/spectronnode12:latest 

test:
  script:
    - cd ElectronJSApp/
    - export DISPLAY=:9.0"
    - Xvfb :9.0 -screen 0 1024x764x24 &
    - npm install
    - npm test