default:
  # This template uses jdk8 for verifying and deploying images
  image: maven:3.6.3-jdk-11

  before_script:
    - echo "Test pipeline" 
  
cache:
  paths:
  - ThalesArc/

test-job:
  tags:
    - docker
  before_script: 
    - dir
    - cd ThalesArc
    - echo "Should do things"
    - mvn dependency:unpack
  script:
    - mvn test