default:
  image: node:14.15.0
  services:
    - qxf2rohand/qxf2_pom_essentials
  tags: 
    - docker 
   
test:
  stage: test 
  script:
    - ls -a
    - cd ElectronJSApp/
    - npm install
    - npm test
    


