image: node:14.15.0

cache:
  paths:
  - ElectronJSApp/node_modules/

all_tests:
  tags:
    - docker
  before_script:
    docker pull selenium/standalone-chrome
  script:
   - cd ElectronJSApp/
   - npm install
   - npm test