default:
  image: node:14.15.0
  
  tags: 
    - docker 
    
  services:
    - selenium/standalone-chrome:latest

test:
  script:
    # Install display server dependencies
    - "apt install xvfb libxtst6 libxss1 libgtk2.0-0 -y"
    # Install core libraries for chromium driver
    - "apt install libnss3 libasound2 libgconf-2-4 -y"
    - cd ElectronJSApp/
    - npm install
    - npm test