default:
  image: node:14.15.0
  before_script:
    - echo "Test and Build pipelines" 
  
cache:
  paths:
  - ElectronJSApp/node_modules/

release-job: 
  tags:
    - docker
  before_script: 
    - cd ElectronJSApp/
    - npm install
  script: 
    - npm run make

test-job:
  tags:
    - docker
  before_script: 
    - cd ElectronJSApp/
    - npm install
  script:
    - npm test
